services:
  postgres:
    image: postgres:latest
    ports:
      - "$PORTS"
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup:/var/lib/postgresql/backup
    container_name: postgres
  postgres_backup:
    image: postgres:latest
    container_name: postgres_backup
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./postgres/backup:/var/lib/postgresql/backup
    entrypoint: >
      bash -c "
      while true; do
        echo 'Backing up...'
        pg_dumpall -h postgres -U $${POSTGRES_USER} > /var/lib/postgresql/backup/tmp.sql &&
        mv /var/lib/postgresql/backup/tmp.sql /var/lib/postgresql/backup/backup_$(date +%Y%m%d%H%M).sql
        ls -tp /var/lib/postgresql/backup/backup_*.sql | tail -n +25 | xargs -I {} rm -- {}
        sleep 3600
      done
      "