services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    network_mode: host
    shm_size: 1gb
    
    environment:
      - PGDATA=/var/lib/postgresql/18/data
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/18/data
      - ./postgres/backup:/var/lib/postgresql/18/backup

    command: >
      postgres
      -c shared_buffers=2GB
      -c effective_cache_size=6GB
      -c work_mem=16MB
      -c maintenance_work_mem=256MB
      -c effective_io_concurrency=200
      -c random_page_cost=1.1

    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost', '-U', '$${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres_backup:
    image: postgres:18
    container_name: postgres_backup
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./postgres/backup:/var/lib/postgresql/18/backup
    entrypoint: >
      bash -c "
      while true; do
        echo 'Backing up...'

        pg_dumpall -h localhost -U $${POSTGRES_USER} > /var/lib/postgresql/18/backup/tmp.sql &&
        mv /var/lib/postgresql/backup/tmp.sql /var/lib/postgresql/18/backup/backup_$(date +%Y%m%d%H%M).sql
        ls -tp /var/lib/postgresql/18/backup/backup_*.sql | tail -n +11 | xargs -I {} rm -- {}

        echo 'Done'

        sleep 86400
      done
      "